<?xml version="1.0" encoding="utf-8"?><Database Name="ZeroCool" Class="ZeroCoolTableClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WARDBUTLER-PC\SQLEXPRESS;Initial Catalog=ZeroCool;Integrated Security=True" SettingsObjectName="ORMs.Properties.Settings" SettingsPropertyName="ZeroCoolConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.XSDTable" Member="XSDTables">
    <Type Name="XSDTable">
      <Column Name="Prim" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>